
name: Promote-to-CI

on: 
   
   workflow_dispatch:
     inputs:
      CurrentBranch:
        description: 'Enter the CURRENT BRANCH NAME'
        required: true
        default: 'preci'
        type: choice
        options:
        - preci
        - CI
        - QA
        - UAT
        
      DestinationBranch:
        type: choice
        description: Enter the DESTINATION BRANCH NAME
        required: true
        default: 'CI'
        options: 
        - preci
        - CI
        - QA
        - UAT
jobs:
  log-the-inputs:
       runs-on: ubuntu-latest
       steps:
          - run: |
              echo "Our CURRENT BRANCH NAME is: $CURRENT_BRANCH_NAME"
            env:
             CURRENT_BRANCH_NAME: ${{ inputs.CurrentBranch }}
             DESTINATION_BRANCH_NAME: ${{ inputs.DestinationBranch }}
             
          
  
  deploy-to-org:
        runs-on: ubuntu-latest
        steps:
            # Checkout the source code
            - name: 'Checkout source code'
              uses: actions/checkout@v2
              
            #  Create promotional Branch     
            - name: 'Creating promotional branch before code promotion'
              shell: bash
              run: |
                  source ./config.sh
                  echo "Creating promotional Branch..."
                  chmod +x scripts/Create_promotional.sh
                  sh scripts/Create_promotional.sh
              env:
               CURRENT_BRANCH_NAME: ${{ inputs.CurrentBranch }}
               DESTINATION_BRANCH_NAME: ${{ inputs.DestinationBranch }}
               PASSWORD: ${{ secrets.PASSWORD }}

            # Install Salesforce CLI
            - name: 'Install Salesforce CLI'
              run: |
                  wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
                  mkdir ~/sfdx
                  tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
                  echo "$HOME/sfdx/bin" >> $GITHUB_PATH
                  ~/sfdx/bin/sfdx version
            
            # Find delta changes
            - name: 'Finding delta changes'
              run: |
                  git remote set-url origin ${SOURCE_REPO_URL}
                  git config --global user.email "${EMAIL_OF_USER_FOR_DESTINATION_REPO}"
                  git config --global user.name "${NAME_OF_USER}"
                  git fetch
                  echo git checkout Promotional-$DESTINATION_BRANCH_NAME-$PipelineName-$BuildPipelineId
                  git checkout Promotional-$DESTINATION_BRANCH_NAME-$PipelineName-$BuildPipelineId
          
                  echo "Before $MANUAL_COMMIT_ID"
                  if [[ "$DEPLOYMENT_MODE" = '' || "$DEPLOYMENT_MODE" = Null || "$DEPLOYMENT_MODE" != 'FULL' ]]; then
                    echo "Before MANUAL_COMMIT_ID $MANUAL_COMMIT_ID"
                    if [[ "$MANUAL_COMMIT_ID" = '' || "$MANUAL_COMMIT_ID" = Null ]]; then 
                       PREVIOUS_SUCCESSFUL_COMMIT_ID=$((curl -u $(gitusername):$(TOKEN) "$(System.TeamFoundationCollectionUri)$(System.TeamProjectId)/_apis/build/builds?resultFilter=succeeded&branchName=refs/heads/CI") | grep -o '"sourceVersion":.*' | cut -d, -f1 | awk -F':' '{print $2}' | sed 's/"//g')
                       echo PREVIOUS_SUCCESSFUL_COMMIT_ID $PREVIOUS_SUCCESSFUL_COMMIT_ID
                       #echo "##vso[task.setvariable variable=COMMIT_ID]$PREVIOUS_SUCCESSFUL_COMMIT_ID"
                       COMMIT_ID=$PREVIOUS_SUCCESSFUL_COMMIT_ID
                    else
                       echo "latest commit id"
                       count1=$(git log --pretty=oneline HEAD...$MANUAL_COMMIT_ID --first-parent | wc -l )
                       if [[ "$count1" = 0 ]]; then
                         PREVIOUS_SUCCESSFUL_COMMIT_ID=$((curl -u $(GIT_USERNAME):$(SOURCE_TOKEN) "$(System.TeamFoundationCollectionUri)$(System.TeamProjectId)/_apis/build/builds?resultFilter=succeeded&branchName=refs/heads/CI") | grep -o '"sourceVersion":.*' | cut -d, -f1 | awk -F':' '{print $2}' | sed 's/"//g')
                         if [[ "$PREVIOUS_SUCCESSFUL_COMMIT_ID" = '' || "$PREVIOUS_SUCCESSFUL_COMMIT_ID" = Null ]]; then
                           #echo "##vso[task.setvariable variable=COMMIT_ID]$MANUAL_COMMIT_ID" 
                           COMMIT_ID=$MANUAL_COMMIT_ID
                           echo manual commit id copied to commit id
                           echo COMMIT_ID $COMMIT_ID 
                         else
                           #echo "##vso[task.setvariable variable=COMMIT_ID]$PREVIOUS_SUCCESSFUL_COMMIT_ID"
                           COMMIT_ID=$PREVIOUS_SUCCESSFUL_COMMIT_ID
                           echo previous commit id copied to commit id
                           echo COMMIT_ID $COMMIT_ID 
                         fi
                       else
                         echo count is not 0, so printing only manual
                         #echo "##vso[task.setvariable variable=COMMIT_ID]$MANUAL_COMMIT_ID"
                         COMMIT_ID=$MANUAL_COMMIT_ID
                         echo COMMIT_ID $COMMIT_ID 
                       fi  
                     fi
                   fi
                   if [[ "$DEPLOYMENT_MODE" = '' || "$DEPLOYMENT_MODE" = Null || "$DEPLOYMENT_MODE" != 'FULL' ]]; then
                     if [[ ( "$MANUAL_COMMIT_ID" = '' || "$MANUAL_COMMIT_ID" = Null ) && ( "$COMMIT_ID" = '' || "$COMMIT_ID" = Null ) ]]; then
                       #echo "##vso[task.setvariable variable=COMMIT_ID]$(git log --format="%P" -n 1)"
                       #echo both commit id and manual commit id is null
                       #echo "##vso[task.setvariable variable=COMMIT_ID]$(Build.SourceVersion)"
                       COMMIT_ID=$(Build.SourceVersion)
                       echo COMMIT_ID $COMMIT_ID 
                     fi
                   fi
              
              
              
            # Authenticate Org
            - name: 'Authenticate CI Org'
              run: sfdx force:auth:jwt:grant --clientid 3MVG9fe4g9fhX0E7Dy5LJtO93WCIHHA0Lsi9uOW5hG3RVbzSsjSB_HmDLIJnUiN.W4xJjFbtW92uXaGbYImnf --jwtkeyfile server.key --username anig2989@gmail.com --instanceurl https://login.salesforce.com 

              
            # Deploy source to CI Org
            - name: 'Push source to CI org'
              run: sfdx force:source:deploy -c -u anig2989@gmail.com -p force-app/main/default
              
            # Merge to destination branch
            - name: 'Merging to destination branch'
              shell: bash
              run: |
                  source ./config.sh
                  git remote set-url origin ${SOURCE_REPO_URL}
                  git config --global user.email "${{ secrets.EMAIL_OF_USER_FOR_DESTINATION_REPO }}"
                  git config --global user.name "${{ secrets.NAME_OF_USER }}"
                  git fetch
                  echo git checkout Promotional-${DESTINATION_BRANCH_NAME}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
                  git checkout Promotional-${DESTINATION_BRANCH_NAME}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
                  echo git checkout ${DESTINATION_BRANCH_NAME}
                  git checkout ${DESTINATION_BRANCH_NAME}
                  echo git merge origin/Promotional-${DESTINATION_BRANCH_NAME}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
                  git merge origin/Promotional-${DESTINATION_BRANCH_NAME}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
                  echo git push origin ${DESTINATION_BRANCH_NAME}
                  git push origin ${DESTINATION_BRANCH_NAME}
                  
              env:
               CURRENT_BRANCH_NAME: ${{ inputs.CurrentBranch }}
               DESTINATION_BRANCH_NAME: ${{ inputs.DestinationBranch }}
                  
              # Delete promotional branch
            - name: 'Deleting promotional branch'
              run: |
                  source ./config.sh
                  git remote set-url origin ${SOURCE_REPO_URL}
                  echo git checkout ${DESTINATION_BRANCH_NAME}
                  git checkout ${DESTINATION_BRANCH_NAME}
                  git push origin --delete Promotional-${DESTINATION_BRANCH_NAME}-${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
        
              env:
               CURRENT_BRANCH_NAME: ${{ inputs.CurrentBranch }}
               DESTINATION_BRANCH_NAME: ${{ inputs.DestinationBranch }}
   
